### ISSUE TITLE
interface {} is nil, not string

### ISSUE THREAD

**Issue by budparr** [poga/netlify-json-api#2]
Thanks for making this!

go version go1.9 darwin/amd64

Running the example from the readme, I'm getting the following error:

```
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.buildFilteredDocumentsForColumn(0x7fff5fbffc27, 0x16, 0x7fff5fbffc17, 0x5, 0xc420050280, 0x4, 0x4, 0xc420086000, 0x7, 0x8, ...)
        /Users/budparr/go/src/github.com/poga/netlify-json-api/main.go:150 +0x1a89
main.main()
        /Users/budparr/go/src/github.com/poga/netlify-json-api/main.go:98 +0x19d0
```

I'm new to go and working through this myself, but thought I'd post it here in case it's something obvious for you.

**Comment by poga** [comment]
Thanks for trying it out!

I've removed the broken commits from `master` branch. It should work now.
Re-install it should fix the issue: `go get -u github.com/poga/netlify-json-api`

**Comment by budparr** [comment]
Perfect, thanks!
